[general]
import = [
    "~/.config/alacritty/themes/themes/monokai.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
decorations = "None"

[font]
size = 10

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Bold Oblique"

[font.italic]
family = "DejaVu Sans Mono"
style = "Oblique"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[terminal]
shell = "/bin/bash"

[mouse]
hide_when_typing = true
